go:
    cgo: true
repository:
    path: github.com/canonical/nrpe_exporter
build:
    binaries:
        - name: nrpe_exporter
    flags: -a -tags netgo,usergo,openssl_static
    static: false
    ldflags: |
      -X github.com/prometheus/common/version.Version={{.Version}}
      -X github.com/prometheus/common/version.Revision={{.Revision}}
      -X github.com/prometheus/common/version.Branch={{.Branch}}
      -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
      -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
tarball:
    files:
        - LICENSE
        - README.md
        - conf/

# crossbuild:
#     platforms:
#         - linux/amd64
